---
title: "Getting started"
format: 
  html:
     page-layout: full
---

## Vaccine Characterisation

```{r, echo=FALSE, eval = TRUE, message=FALSE, warning=FALSE}
# load results
library(omopgenerics)
library(here)
results <- importSummarisedResult(path = here(""))
```

### Eligibles ttrition plot

```{r, echo=FALSE, eval = TRUE, message=FALSE, warning=FALSE}
library(CohortCharacteristics)
plotCohortAttrition(result = results)
```

### Vaccination campaign Characterisation

```{r, echo=FALSE, eval = TRUE, message=FALSE, warning=FALSE}
tableCharacteristics(result = results, header="Vaccination campaign")
```

## Plots

::: {layout-ncol="2"}
### Overall Vaccination

```{r, echo=FALSE, eval = TRUE, message=FALSE, warning=FALSE}
library(dplyr)
library(readr)
library(ggplot2)

plot_90 <- read.csv(here::here("plot_90.csv"))
plot_dose <- read.csv(here::here("plot_dose.csv"))

plot_90 <- plot_90 |>
  mutate(cohort_start_date = as.Date(cohort_start_date))

plot_dose <- plot_dose |>
  mutate(cohort_start_date = as.Date(cohort_start_date))
  
plot_dosef <- plot_dose |> filter(n>"5")


plot_with_campaign <- plot_dosef |>
  filter(cohort_start_date>as.Date("2023-08-02") & cohort_start_date<as.Date("2026-01-01"))|>
  mutate(vaccination_campaign = case_when(
    cohort_start_date>=as.Date("2023-08-02") & cohort_start_date<=as.Date("2024-01-31") ~ "A_2023",
    cohort_start_date>=as.Date("2024-04-15") & cohort_start_date<=as.Date("2024-06-03") ~ "S_2024",
    cohort_start_date>=as.Date("2024-08-03") & cohort_start_date<=as.Date("2024-12-20") ~ "A_2024",
    cohort_start_date>=as.Date("2025-04-01") & cohort_start_date<=as.Date("2025-06-01") ~ "S_2025",
    cohort_start_date>=as.Date("2025-07-01") & cohort_start_date<=as.Date("2026-01-01") ~ "A_2025"),
  )

campaign_intervals <- plot_with_campaign |>
  group_by(vaccination_campaign) |>
  summarise(
    first_date = min(cohort_start_date, na.rm = TRUE),
    last_date  = max(cohort_start_date, na.rm = TRUE)
  ) |>
  ungroup()

campaign_intervals <- campaign_intervals |>
    filter(!is.na((vaccination_campaign)))

plot_dosef <- plot_dosef |>
  mutate(
    dose = factor(
      dose,
      levels = paste0(1:10, " dose"),
      ordered = TRUE
    )
  )

plot_with_campaign <- plot_with_campaign |>
  mutate(
    dose = factor(
      dose,
      levels = paste0(1:10, " dose"),
      ordered = TRUE
    )
  )
graph <- ggplot(plot_dosef, aes(x = cohort_start_date, y = n_dose, fill = dose)) +
  geom_rect(data = campaign_intervals,
            aes(xmin = first_date, xmax = last_date, ymin = 0, ymax = Inf),
            inherit.aes = FALSE, alpha = 0.15, fill = "grey25") +
  geom_col(position = "stack", width = 1) +
  scale_x_date(date_breaks = "3 month", date_labels = "%Y-%m", expand = c(0, 0)) +
  theme_bw() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Date", y = "# vaccines")

print(graph)
```

### Vaccination Campaigns

```{r, echo=FALSE, eval = TRUE, message=FALSE, warning=FALSE}
graph2 <- ggplot(plot_with_campaign,
       aes(x = cohort_start_date, y = n_dose, fill = dose)) +
  geom_col() +
  facet_grid(vaccination_campaign ~ ., scales = "free_x", space = "free_x") +
  scale_x_date(date_breaks = "3 month", date_labels = "%Y-%m", expand = c(0, 0))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Date", y = "# vaccines")

print(graph2)
               
```
:::
